/**
 * Re-exports of Prisma-generated types and conveniences.
 *
 * Keeping this here means consumers of `@vrs/db` only ever import from one
 * package, never from `@prisma/client` directly. That gives us a stable
 * boundary if we ever swap ORMs or want to wrap the types.
 */

export type {
  User,
  Account,
  Session,
  OtpCode,
  ApiKey,
  Project,
  Track,
  Clip,
  Asset,
  Transcript,
  TranscriptSegment,
  Caption,
  Voice,
  Voiceover,
  AiJob,
  Export,
  PublishTarget,
  PublishJob,
  Template,
  Plan,
  Subscription,
  Invoice,
  UsageRecord,
  Notification,
  AuditLog,
  SupportTicket,
  TicketMessage,
  AbuseReport,
  WebhookDelivery,
  FeatureFlag,
} from '@prisma/client';

export {
  UserRole,
  AccountStatus,
  OtpPurpose,
  AuthProvider,
  ProjectType,
  ProjectStatus,
  ProjectAspectRatio,
  TrackKind,
  ClipSource,
  AssetKind,
  AssetSource,
  AssetStatus,
  TranscriptStatus,
  VoiceKind,
  VoiceStatus,
  VoiceProvider,
  VoiceoverStatus,
  AiJobKind,
  AiJobStatus,
  ExportFormat,
  ExportStatus,
  PlanCode,
  BillingInterval,
  SubscriptionStatus,
  InvoiceStatus,
  UsageKind,
  NotificationKind,
  TicketStatus,
  TicketPriority,
  AbuseReason,
  AbuseStatus,
  PublishProvider,
  PublishStatus,
  WebhookSource,
  WebhookStatus,
} from '@prisma/client';
